+incdir+${VERIF}
+incdir+${VERIF}/run
+incdir+${VERIF}/tb_top
+incdir+${VERIF}/tests
+incdir+${VERIF}/sv
+incdir+${VERIF}/sv/agents
+incdir+${VERIF}/sv/register
+incdir+${VERIF}/sv/sequences
+incdir+${VERIF}/sv/sequences/dt
+incdir+${VERIF}/sv/sequences/regs
+incdir+${VERIF}/sv/sequences/dfi

$APB_PKG
$DFI_PKG
$LPDDR5_PKG
$WDDR_PKG
${VERIF}/sv/agents/mm/wav_mm.sv
${VERIF}/sv/agents/APB/apb_to_ahb.v
${VERIF}/tb_top/wddr_tb_top.sv